DROP TABLE IF EXISTS reservations;
DROP TABLE IF EXISTS rooms;
DROP TABLE IF EXISTS guests;
DROP TABLE IF EXISTS room_types;

CREATE TABLE room_types
(
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_name       VARCHAR(50)    NOT NULL UNIQUE,
    capacity        INT            NOT NULL CHECK (capacity > 0),
    price_per_night DECIMAL(10, 2) NOT NULL CHECK (price_per_night >= 0)
);

CREATE TABLE rooms
(
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_number  VARCHAR(10) NOT NULL UNIQUE,
    floor_number INT         NOT NULL,
    status       VARCHAR(20) NOT NULL CHECK (status IN ('свободна', 'заета', 'ремонт')),
    room_type_id INT         NOT NULL,
    CONSTRAINT fk_room_type
        FOREIGN KEY (room_type_id)
            REFERENCES room_types (id)
);

CREATE TABLE guests
(
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(50)  NOT NULL,
    last_name  VARCHAR(50)  NOT NULL,
    phone      VARCHAR(20)  NOT NULL UNIQUE,
    email      VARCHAR(100)
);

CREATE TABLE reservations
(
    id                 INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guest_id           INT            NOT NULL,
    room_id            INT            NOT NULL,
    check_in           DATE           NOT NULL,
    check_out          DATE           NOT NULL,
    reservation_status VARCHAR(20)    NOT NULL CHECK (reservation_status IN ('активна', 'приключена', 'отказана')),
    total_price        DECIMAL(10, 2) NOT NULL,
    CONSTRAINT fk_guest
        FOREIGN KEY (guest_id)
            REFERENCES guests (id),
    CONSTRAINT fk_room
        FOREIGN KEY (room_id)
            REFERENCES rooms (id),
    CONSTRAINT check_dates CHECK (check_out > check_in)
);

INSERT INTO room_types (type_name, capacity, price_per_night)
VALUES ('Единична', 1, 80),
       ('Двойна', 2, 120),
       ('Апартамент', 4, 250);

INSERT INTO rooms (room_number, floor_number, status, room_type_id)
VALUES ('101', 1, 'свободна', 1),
       ('102', 1, 'свободна', 2),
       ('201', 2, 'заета', 2),
       ('301', 3, 'ремонт', 3);

INSERT INTO guests (first_name, last_name, phone, email)
VALUES ('Иван', 'Петров', '0888123456', 'ivan@email.com'),
       ('Мария', 'Георгиева', '0888234567', 'maria@email.com'),
       ('Николай', 'Стоянов', '0888345678', 'nikolay@email.com');

INSERT INTO reservations (guest_id, room_id, check_in, check_out, reservation_status, total_price)
VALUES (1, 2, DATE '2026-04-10', DATE '2026-04-15', 'активна', 600),
       (2, 3, DATE '2026-03-01', DATE '2026-03-05', 'приключена', 480);